remote_theme: eliottvincent/bay

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Blog  # <-- blog.md
    
footer:
  show_powered_by: true
  contact:
    - name: Email
      value: rwiddhi.chakraborty@usi.ch
      link: mailto:rwiddhi.chakraborty@usi.ch
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/rwiddhic/
    - name: GitHub
      link: https://github.com/rwchakra
